version: '3'

services:

  flaskapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src

  maps:
    image: klokantech/osmnames-sphinxsearch
    ports:
      - 777:80
    volumes:
      - ./map_data/index:/data/index
      - ./map_data/input:/data/input

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./central.conf:/etc/nginx/central.conf
    depends_on:
      - flaskapp
